name: feature_engineering

channels:
  - esri
  - conda-forge
  - defaults

dependencies:
  - arcgis==1.7.0
  - dask
  - nodejs
  - pillow
  - pyarrow
  - pylint
  - pytest
  - python-dotenv
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - pip:
    - ipykernel
  
